### ISSUE TITLE
Month value is off by 1

### ISSUE THREAD

**Issue by lennard0011** [drautb/epoch-converter#10]
The value shown for the month is off by 1. As you can see in the example below the month of March, but the date notes 2023-**02**-29 thus February 23rd. I can reliably reproduce the issue. Let me know if you want more information or cases. 

![image](https://user-images.githubusercontent.com/16563680/228531478-f765191f-63c9-4b4a-a23c-fbed855141fd.png)

**Comment by Tim-Vrhn** [comment]
Hi @drautb, I've created a PR for this issue: https://github.com/drautb/epoch-converter/pull/11

Are you able to have a look and possibly deploy this change to the Chrome Web Store?

**Comment by drautb** [comment]
Thanks for the PR. New version has been submitted to the web store, will auto-publish pending review.
