### ISSUE TITLE
Only invoke when a 10-digit number is highlighted.

### ISSUE THREAD

**Issue by drautb** [drautb/epoch-converter#3]

**Comment by Tim-Vrhn** [comment]
I see this issue was implemented but the chrome extension was never updated with this feature. Would be highly appreciated if you could run the update!

**Comment by drautb** [comment]
I submitted an updated version to the Chrome Web Store - it's pending review right now. They say that can take a couple weeks, but once it's done this will be live.

**Comment by Tim-Vrhn** [comment]
Thank you very much @drautb, I see the update is already live. Makes this tool even better!
